"""Index

Revision ID: e3ae66ffdfb5
Revises: 3338888ab5a0
Create Date: 2023-12-20 16:43:57.304594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ae66ffdfb5'
down_revision: Union[str, None] = '3338888ab5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Adress', sa.Column('Index', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Adress', 'Index')
    # ### end Alembic commands ###
