"""remake

Revision ID: 9299e9e8130b
Revises: 211ab7824381
Create Date: 2023-12-23 14:09:10.071129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9299e9e8130b'
down_revision: Union[str, None] = '211ab7824381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Orders', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('money', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'notes')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'money')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'nickname')
    op.drop_column('Orders', 'notes')
    op.drop_column('Orders', 'created_at')
    # ### end Alembic commands ###
