"""Street

Revision ID: bd576550cac6
Revises: e3ae66ffdfb5
Create Date: 2023-12-20 16:46:21.554934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd576550cac6'
down_revision: Union[str, None] = 'e3ae66ffdfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Adress', sa.Column('Street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Adress', 'Street')
    # ### end Alembic commands ###
